# (c) Copyright 2018 DataNexus Inc.  All Rights Reserved.
#
# handlers used during kibana installation
---
- name: restart kibana
  systemd:
    name: "{{ kibana.service_name }}"
    state: restarted
  become: true

- name: reload systemd
  command: systemctl daemon-reload
  become: true